# Generated by Django 4.1.6 on 2023-02-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topico_pergunta_host_resposta_pergunta_topico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='tag',
            new_name='corpo',
        ),
    ]
