# Generated by Django 4.1.6 on 2023-02-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tag_pergunta_corpo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['-criado', '-editado']},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['-criado', '-editado']},
        ),
    ]

