# Generated by Django 4.1.6 on 2023-02-17 21:24

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pergunta_options_alter_resposta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='corpo',
            field=models.CharField(max_length=600),
        ),
    ]



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pergunta_options_alter_resposta_options'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE main_resposta DROP COLUMN curtido;'),
    ]


